#!/usr/bin/env python
"""Tools for loading and cleaning the raw .xls data from surveymonkey."""

import os

import pandas

# this is the Excel file generated by surveymonkey, renamed
RAW_DATA_FILENAME = "survey-raw-data.xls"

# some platform-independent path manipulation to get to the data/ directory
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_DIR = os.path.join(BASE_DIR, "data")
RAW_DATA_FILE = os.path.join(DATA_DIR, RAW_DATA_FILENAME)

COLUMN_NAMES = {
0 : "RespondentID",
1 : "CollectorID",
2 : "StartDate",
3 : "EndData",
4 : "IP Address",
5 : "Email Address",
6 : "First Name",
7 : "Last Name",
8 : "(Blank)",
9 : "Cabbagetown or Reynoldstown?",
10: "Other Neighborhood?",
11: "Street",
12: "Age",
13: "Number Over 16",
14: "Number Under 16",
15: "Commute % Drive Alone",
16: "Commute % Carpool",
17: "Commute % MARTA Bus",
18: "Commute % MARTA Rail",
19: "Commute % Bicycle",
20: "Commute % Walk",
21: "Commute % Ride Service",
22: "Commute % Motorcycle/Scooter",
23: "Commute % Telecommute",
24: "Non-Commute % Drive Alone",
25: "Non-Commute % Carpool",
26: "Non-Commute % MARTA Bus",
27: "Non-Commute % MARTA Rail",
28: "Non-Commute % Bicycle",
29: "Non-Commute % Walk",
30: "Non-Commute % Ride Service",
31: "Non-Commute % Motorcycle/Scooter",
32: "% Trips Within C/R Town",
33: "Top Outside Destination",
34: "Y/N - Walk for Recreation",
35: "Y/N - Bike for Recreation",
36: "Other Recreation",
37: "RANK - Ped Safety",
38: "RANK - Beltline",
39: "RANK - Parking",
40: "RANK - Cycling Safety",
41: "RANK - Traffic Increase",
42: "RANK - MARTA Bus Exp.",
43: "RANK - MARTA Rail Exp.",
44: "RANK - Reduced Speeding",
45: "RANK - Road Condition",
46: "RANK - Sidewalk Condition",
47: "Other Concerns",
48: "Your Solutions",
}

def load_xls():
    """Load an Excel file into a pandas DataFrame."""
    xls = pandas.ExcelFile(RAW_DATA_FILE)
    dataframe = xls.parse(xls.sheet_names[0])
    return dataframe


def rename_columns(dataframe):
    """Fix the column names."""
    for index in xrange(0, dataframe.columns.size):
        dataframe.columns.values[index] = COLUMN_NAMES[index]
    return dataframe


def load_and_clean_data():
    """Load data and run all cleaning steps."""
    raw_data = load_xls()
    # cleaning steps ...
    data = rename_columns(raw_data)
    # ...
    return data


if __name__ == "__main__":
    CLEAN_DATA = load_and_clean_data()
    print repr(CLEAN_DATA)
